In [ ]:
# TASK 1_5
import pandas as pd
data = [[1,'a'],[1,'b'],[1,'b'],[2,'c'],[2,'d'],[2,'g']]
df = pd.DataFrame(data, columns=['id', 'Value'])
df
df.groupby('id', as_index=False).agg(','.join)


id  Value
0   1  a,b,b
1   2  c,d,g

In [ ]:
# TASK 1_2
def squarsum(n):
  sum=0
  i=1
  while(i<=n):
    sum=sum+(i*i)
    i+=1
  return(sum)

n=int(input('\n Enter number N \n'))
print(squarsum(n))



 Enter number N 
4
30


In [ ]:
# TASK 1_6
def stopwrd(str2):
  stop=['it','the','all','is','.',',','this']
  cnt=0
  for i in str2.split():
    if i not in stop:
      cnt=cnt+1
  print(cnt)

str1=input('\n Enter Input sentences: \n')
str2=str1.lower()
stopwrd(str2)



 Enter Input sentences: 
The Matrix is everywhere. It is all around us. Even now, in this very room.
9


In [ ]:
# TASK 1_7

import pandas as pd
import numpy as np

def convert_my_string(my_string, my_k):

   for index in range(len(my_string)):
      if index % my_k == 0:
         sub = my_string[index:index+my_k]
         my_list = []
         for j in sub:
            my_list.append(j)
         print(' '.join(my_list))
   b=np.array(my_list)
   c=np.unique(b,axis=0)
   if (len(c[ :0])==len(c[ :1])==len(c[ :2])==my_k):
        print("Good")
   else:
        print("Bad")
    

my_string=input('\nEnter Input 9 digits\n')
k=3
convert_my_string(my_string,k)



Enter Input 9 digits
123145789
1 2 3
1 4 5
7 8 9
Bad


In [ ]:
import numpy as np
b = np.array([[1, 2, 0], [1, 1, 7], [2, 8, 4]])
print(b)
c=np.unique(b,axis=0)
print(len(c))

[[1 2 0]
 [1 1 7]
 [2 8 4]]
3


In [ ]:
#TASK 1_4
import pandas as pd
import numpy as np
def lag (datafr,lagv,col,dropna=True):
    datafr['c_lag1']=datafr[col].shift(lagv)
    print(datafr)


data = {'a':[2, 3, 4],
        'b':[5, 6, 7],
        'c':[10,9,8]}
datafr=pd.DataFrame(data)
lag(datafr,lagv=1,col='a')


   a  b   c  c_lag1
0  2  5  10     NaN
1  3  6   9     2.0
2  4  7   8     3.0


In [ ]:
  # TASK 1_3
#str1=input("\nEnter input String\n")
def wovel (str1):
    wovles=('a','e','i','o','u')
    cnt=0
    for i in str1.lower():
      if i in wovles:
          cnt+=1        
    print(cnt)

str1=input("\nEnter input String\n")
wovel(str1)


Enter input String
mohini
3
